---
- name: Add apt key for PHP ppa
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
    state: present

- name: Add apt repository for PHP
  apt_repository:
    repo: "ppa:ondrej/php/ubuntu"
    state: present

- name: Install PHP
  apt:
    name: "php{{ php_version }}"
    state: present

- name: Install required php packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php{{ php_version }}-bcmath
    - php{{ php_version }}-cli
    - php{{ php_version }}-common
    - php{{ php_version }}-curl
    - php{{ php_version }}-dom
    - php{{ php_version }}-fpm
    - php{{ php_version }}-gd
    - php{{ php_version }}-gmp
    - php{{ php_version }}-intl
    - php{{ php_version }}-json
    - php{{ php_version }}-ldap
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-memcached
    - php{{ php_version }}-mysql
    - php{{ php_version }}-opcache
    - php{{ php_version }}-pgsql
    - php{{ php_version }}-sqlite3
    - php{{ php_version }}-xml

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/bin --filename=composer
  state: present

- name: Configure composer cache directory to avoid using slow NFS
  shell: composer config --global cache-dir /dev/shm/composer/cache
  state: present

- name: Download and install PHPUnit
  get_url:
    url: https://phar.phpunit.de/phpunit.phar
    dest: /usr/bin/phpunit
    mode: 0755

- name: Copy php-fpm pool config
  template:
    src: www.conf
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
  notify:
    - restart php-fpm