---
- name: Add apt key for Nginx ppa
  apt_key:
    url: "http://nginx.org/keys/nginx_signing.key"

- name: Add apt repository for Nginx
  apt_repository:
    repo: "ppa:nginx/stable"

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Copy nginx config
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Remove default virtual host
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx

- name: Default virtual host
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart nginx