---
- name: Install required base packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - aptitude
      - beanstalkd
      - curl
      - gcc
      - git
      - iptraf
      - iftop
      - iotop
      - lrzsz
      - lsof
      - memcached
      - mtr-tiny
      - openssh-client
      - python3
      - python3-pip
      - rsync
      - sysstat
      - telnet
      - tmux
      - unzip
      - vim
      - wget
      - whois
      - zip

- name: Adding group {{ www_group }}
  group:
    name: "{{ www_group }}"
    gid: 501

- name: Adding user {{ www_user }}
  user:
    name: "{{ www_user }}"
    group: "{{ www_group }}"
    uid: 501
    password: "{{ www_password }}"
    shell: "/bin/bash"

- name: Adding group {{ mysql_group }}
  group:
    name: "{{ mysql_group }}"
    gid: 502

- name: Adding user {{ mysql_user }}
  user:
    name: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    uid: 502
    shell: "/sbin/nologin"

- name: Enable password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication yes"
  notify: restart sshd

- name: Add sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/sudoers
    validate: 'visudo -cf %s'
    mode: 0440

- name: Editor version selected
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Timezone
  lineinfile:
    dest: /etc/environment
    line: "TZ={{ timezone  }}"
    state: present
