---
- name: Install MySQL
  apt:
    name: mysql-server
    state: present

- name: Copy mysql config
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
    - restart mysql

- name: Install MySQL required packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python-mysqldb

- name: Update mysql root password for all root accounts
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password | quote }}"
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password | quote }}"
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  run_once: true
