---
- name: Import MySQL public GPG Key
  apt_key:
    url: https://repo.mysql.com/RPM-GPG-KEY-mysql
    id: A4A9406876FCBD3C456770C88C718D3B5072E1F5
    state: present

- name: Add MySQL 8 repository
  apt_repository:
    repo: "deb https://repo.mysql.com/apt/ubuntu {{ ansible_lsb.codename }} mysql-8.0"
    state: present

- name: Install MySQL
  apt:
    name: mysql-community-server
    state: present

- name: Copy MySQL config
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
    - restart mysql

- name: Install MySQL required packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3-mysqldb

- name: Check if root password is set
  command: "mysql -u root -p'{{ mysql_root_password }}' -e 'SELECT 1'"
  ignore_errors: yes
  register: mysql_root_password_check

# @TODO: root@localhost `auth_socket` plugin. @see https://github.com/ansible/ansible/pull/44267
- name: Set MySQL root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password | quote }}"
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - "127.0.0.1"
    - "::1"
    - "localhost"
  when: mysql_root_password_check.rc == 1
