---
- name: Add apt key for redis ppa
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 136221EE520DDFAF0A905689B9316A7BC7917B12
    state: present

- name: Add apt repository for redis
  apt_repository:
    repo: "ppa:chris-lea/redis-server"
    state: present

- name: Install redis
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - redis-server
      - redis-tools