---
- name: Install MongoDB Keyring
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    state: present

- name: Install MongoDB Repository
  apt_repository:
    repo: "deb [arch=amd64] {{ mongodb_mirror }}/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} multiverse"
    state: present
    update_cache: yes

# By default, MongoDB would not be started and enabled after installation on
# Ubuntu. So we don't need to stop MongoDB manually, but do need to manually
# reload systemd daemon to load the MongoDB systemd unit before enable/start it.
- name: Ensure MongoDB is installed
  package:
    name: mongodb-org
    state: present

- name: Ensure MongoDB is configured
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify: restart mongodb

- name: Create db path if it does not exist
  file:
    path: "{{ mongodb_db_path }}"
    state: directory
    owner: mongodb
    group: mongodb
    mode: 0755

- name: Ensure MongoDB is running and enabled on boot
  service:
    name: mongod
    state: started
    enabled: yes