---
- name: Install Samba packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - samba-common
    - samba
    - samba-client

- name: Create Samba www root directory
  file:
    state: directory
    path: "{{ document_root }}"
    owner: "{{ samba_user }}"
    group: "{{ www_group }}"
    mode: "0755"

- name: Samba configuration
  template:
    dest: /etc/samba/smb.conf
    src: smb.conf.j2
    validate: 'testparm -s %s'
  notify:
    - restart samba

- name: Start Samba service(s)
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - smbd
    - nmbd

- name: Create Samba users if they don't exist yet
  shell: >
    (pdbedit --user={{ item.name }} 2>&1 > /dev/null) \
    || (echo {{ item.password }}; echo {{ item.password }}) \
    | smbpasswd -s -a {{ item.name }}
  with_items:
    - name: "{{ samba_user }}"
      password: "{{ samba_password }}"
  register: create_user_output
  changed_when: "'Added user' in create_user_output.stdout"
