---
- hosts: all
  become: true
  vars:
    timezone: Asia/Shanghai
    document_root: /home/www/projects
    www_user: www
    www_group: www
    # 123456
    www_password: "$6$C075HPLTAvTU$DQ4CT8PL6sBT0NT.iU5VusBEW31TlTYr0os.BqZLhfbIG7BnqncEMl3Jp2.2smhL4J2VJ/Gk2CFkCHYAQbtAj/"
    sudo:
      users:
        - www
    mysql_user: mysql
    mysql_group: mysql
    mysql_root_password: "123456"
    mysql_db_path: /var/lib/mysql
    mysql_bind_ip: "0.0.0.0"
    gopath: "/home/www/projects/golang"
    samba_www_root: "/home/www"
    samba_user: www
    samba_group: www
    samba_password: "123456"
    mongodb_version: "4.4"
    mongodb_db_path: /var/lib/mongodb
    mongodb_bind_ip: "0.0.0.0"
    # http://repo.mongodb.org
    mongodb_mirror: "https://mirrors.tuna.tsinghua.edu.cn/mongodb"
    # https://download.docker.com
    docker_mirror: "https://mirrors.tuna.tsinghua.edu.cn/docker-ce"
  pre_tasks:
    - name: update apt cache and upgrade apt packages
      apt:
        update_cache: yes
        cache_valid_time: 7200
        upgrade: yes
  roles:
    - base
    - nginx
    - mysql
    - php
    - golang
    - redis
    - nodejs
    - samba
    - mongodb
    - docker
