---
- hosts: all
  become: true
  vars:
    timezone: Asia/Shanghai
    document_root: /opt/projects
    www_user: www
    www_group: www
    mysql_user: mysql
    mysql_group: mysql
    mysql_root_password: 123456
    mysql_db_path: /var/lib/mysql
    mysql_bind_ip: 127.0.0.1
    gopath: "/opt/projects/golang"
    samba_www_root: "/opt/projects"
    samba_user: www
    samba_group: www
    samba_password: 123456
    mongodb_version: 3.6
    mongodb_db_path: /var/lib/mongodb
    mongodb_bind_ip: 127.0.0.1
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
  roles:
    - base
    - nginx
    - mysql
    - php
    - golang
    - redis
    - nodejs
    - samba
    - mongodb