---
- name: Get rust user home directory
  command: "bash -ls"
  args:
    stdin: "cd && pwd"
  become: true
  become_user: "{{ rust_user }}"
  changed_when: false
  register: rust_user_home_check

- name: Set rust user home directory
  set_fact:
    rust_user_home: "{{ rust_user_home_check.stdout_lines | first }}"

- name: Set rust user path
  set_fact:
    rust_user_path: "{{ rust_user_home }}/.cargo/bin:{{ rust_user_home }}/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

- name: Check if rustup is installed
  stat:
    path: "{{ rust_user_home_check.stdout_lines | first }}/.rustup"
  register: rustup_directory_check
  become: true
  changed_when: false
  failed_when: false

- name: Set rustup status
  set_fact:
    rustup_is_installed: "{{ rustup_directory_check.stat.exists }}"

- name: Check if rls is installed
  stat:
    path: "{{ rust_user_home }}/.cargo/bin/rls"
  register: rls_binary_check
  become: true
  changed_when: false
  failed_when: false

- name: set rls status
  set_fact:
    rls_is_installed: "{{ rls_binary_check.stat.exists }}"

- name: Fetch rustup installer
  uri:
    url: https://sh.rustup.rs
    method: GET
    status_code: 200
    return_content: true
  register: rustup_installer_response
  when: not (rustup_is_installed | bool)

- name: Install rustup as the user
  command: sh -s -- -y --no-modify-path
  args:
    stdin: "{{ rustup_installer_response.content }}"
  become: true
  become_user: "{{ rust_user }}"
  when: not (rustup_is_installed | bool)

- name: Set default toolchain
  command: "rustup default stable-x86_64-unknown-linux-gnu"
  environment:
    PATH: "{{ rust_user_path }}"
  become: true
  become_user: "{{ rust_user }}"
  when: not (rustup_is_installed | bool)

- name: Install musl toolchain
  command: "rustup target add x86_64-unknown-linux-musl"
  args:
    creates: "{{ rust_user_home }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl"
  environment:
    PATH: "{{ rust_user_path }}"
  become: true
  become_user: "{{ rust_user }}"
  when: rust_dev_include_musl

  # install man pages
- name: Create man path
  file:
    path: "{{ rust_user_home }}/.local/share/man/man1"
    state: directory
    owner: "{{ rust_user }}"
    group: "{{ rust_user }}"
    recurse: true
  become: true
  become_user: "{{ rust_user }}"

- name: Install man pages
  command: rsync -a "{{ rust_user_home }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/man/man1/" "{{ rust_user_home }}/.local/share/man/man1/"
  become: true
  become_user: "{{ rust_user }}"
  changed_when: false

# install bash completions
- name: Create bash completion path
  file:
    path: "{{ rust_user_home }}/.local/share/bash-completion/completions"
    state: directory
    owner: "{{ rust_user }}"
    group: "{{ rust_user }}"
    recurse: true
  become: true
  become_user: "{{ rust_user }}"

- name: Generate rustup completions
  command: "{{ rust_user_home }}/.cargo/bin/rustup completions bash"
  environment:
    PATH: "{{ rust_user_path }}"
  become: true
  become_user: "{{ rust_user }}"
  register: rustup_completions
  changed_when: false

- name: Write rustup completions
  copy:
    content: "{{ rustup_completions.stdout }}"
    dest: "{{ rust_user_home }}/.local/share/bash-completion/completions/rustup"
    mode: "0644"
    owner: "{{ rust_user }}"
    group: "{{ rust_user }}"
  become: true
  become_user: "{{ rust_user }}"

- name: Install bash completions
  command: rsync -a "{{ rust_user_home }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/etc/bash_completion.d/" "{{ rust_user_home }}/.local/share/bash-completion/completions/"
  become: true
  become_user: "{{ rust_user }}"
  changed_when: false
